#!/bin/bash


function getAddonsMakeFileExists {
	if [ -f addons.make ]
	then
		local result=$(cat addons.make)
	fi
	validate "$result" "Directory seems to not contain an OF project, addons.make was not found."
	echo "$result"
}

function getInfo {
	getOrigin
	getBranch
	getCommit
}


function getOrigin {
	local result=$(echo `git remote show origin | grep Fetch |  sed s_\ \ Fetch\ URL:\ __`)
	validate "$result" "Couldn't get the repository origin"
	echo "$result"
}

function getBranch {
	local result=$(echo `git branch | sed s_*\ __`)
	validate "$result" "Couldn't get the current branch."
	echo "$result"
}

function getCommit {
	local result=$(echo `git rev-parse HEAD`)
	validate "$result" "Couldn't get the current commit."
	echo "$result"
}



function validate {
	if [ -z "$1" ]
		then
			echo "$2"
			echo "Terminating script now!" 
			exit
	fi
}

getAddonsMakeFileExists
#getInfo